Создание массивов

In [1]:
import numpy as np

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([1., 2., 3., 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.random((3, 3))

array([[0.24038024, 0.56385997, 0.03700783],
       [0.38276681, 0.22015392, 0.27908546],
       [0.31125502, 0.2236597 , 0.72516897]])

In [2]:
#случайные значение с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (3, 3))

array([[-1.33050136, -2.36309698,  1.7527672 ],
       [-1.42143876,  0.64292877, -0.30777255],
       [ 1.35703769, -0.10098483, -0.26786338]])

In [13]:
#Создаем массив размером 3 х 3 случайных целых числа в промежутке [0, 10]
np.random.randint(0, 10, (3, 3))

array([[0, 2, 8],
       [0, 7, 1],
       [3, 5, 7]])

In [14]:
#Создаем единичную матрицу размером 3 х 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Создаем неинициализированный массив из трех целочисленных значений. Значениями будут произвольные, случайно оказавшиеся
#в соответ. ячейках памяти данные
np.empty(3)

array([1., 1., 1.])